
DatasetsDirectory: "/Users/olivergrainge/Documents/github/Datasets"
LocalFeatureDetector: "SIFT" # Either SIFT or HARRIS
LocalFeatureDescriber: "SIFT"
LocalFeatureTracker: "KLT" # Either KLT or BruteForce