
DatasetsDirectory: "/Users/olivergrainge/Documents/github/Datasets"
LocalFeatureDetector: "SIFT" # Either SIFT or HARRIS
LocalFeatureDescriber: "SIFT"
LocalFeatureTracker: "Matcher" # Either KLT or BruteForce
MotionEstimation: "3d2d" # Either 2d2d, 3d2d or 3d3d