


DatasetsDirectory: "/Users/olivergrainge/Documents/github/Datasets"
LocalFeatureDetector: "SIFT" # Either SIFT or HARRIS
LocalFeatureDescriber: "SIFT"
LocalFeatureTracker: "KLT" # Only KLT available at the moment
MotionEstimation: "3d2d" # Either 2d2d, 3d2d or 3d3d (Only 3d2d available at the moment)

Tracking: 
  InlierThreshold: 0.8
  Probability: 0.9999


Stereo: 
  MaxFeatures: 250
  InlierThreshold: 0.8
  Probability: 0.9999
  MaxReprojError: 0.5
  min_x: -12
  max_x: 12
  min_y: -8
  max_y: 2
  min_z: 2


